import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import ENS, { getEnsAddress } from '@ensdomains/ensjs'


export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Tree</h1>
    </div>
  )
}
