import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Diagram from '../components/diagram'
import React from "react";

export default function Home() {

  return (
    <div className={styles.container}>
      <Head>
        <title>ORG3</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <h1>Tree</h1>
      <Diagram></Diagram>
    </div>
  )
}
